# Generated by Django 2.2.2 on 2019-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='best_sites_img')),
                ('content', models.TextField(max_length=200)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
            ],
        ),
    ]
