# Generated by Django 2.2.2 on 2019-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0002_best_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHG_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('direct_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
