# Generated by Django 2.2.2 on 2019-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0004_auto_20190701_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhg_models',
            name='date_added',
            field=models.CharField(max_length=30),
        ),
    ]
