# Generated by Django 2.2.2 on 2019-07-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0005_auto_20190701_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhg_models',
            name='date_added',
        ),
    ]
