# Generated by Django 2.2.2 on 2019-07-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0007_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
